---
# tasks file for deploy_wordpress

- name: Download wp
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=yes

- name: Extract Wordpress
  unarchive:
    src=/tmp/wordpress.tar.gz
    dest=/var/www/site.ru
    copy=no

- name: Change wp.conf
  copy:
    src: wp-config.php
    dest: "{{ destWpconf }}"
    owner: www-data
    group: www-data
    mode: '0644'

