---
# tasks file for deploy_apache

- name: Install Apach2
  apt: name={{ item }} state=latest
  loop: ['apache2', 'libapache2-mod-rpaf']
  notify:
    - started apache2



- name: apache2 listen on port 81
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 81" state=present

- name: Change VirtualHosts
  copy:
    src: site-ru.conf
    dest: "{{ destinSites }}"
    owner: root
    group: root
    mode: '0644'

- name: Change VirtualHosts2
  copy:
    src: site-2-ru.conf
    dest: "{{ destinSites }}"
    owner: root
    group: root
    mode: '0644'

- name: a2dissite default
  command: a2dissite "000-default.conf"
  notify:
    - restart apache2

- name: a2ensite site-ru
  command: a2ensite "site-ru.conf"
  notify:
    - restart apache2

- name: a2ensite site-2-ru
  command: a2ensite "site-2-ru.conf"
  notify:
    - restart apache2


- name: Change apache.conf
  template:
    src: apache2.conf
    dest: "{{ destinApache }}"
    owner: root
    group: root
    mode: '0644'


- name: Change mpm-prefork.conf
  template:
    src: mpm_prefork.conf
    dest: "{{ destinMods }}"
    owner: root
    group: root
    mode: '0644'

- name: restart apache2
  service:
    name: apache2
    state: restarted
